# Generated by Django 5.1 on 2024-08-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_remove_property_price_remove_property_title_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Tenant",
        ),
    ]
